export enum NotificationType {
  ISSUE_ASSIGNED = 'issue_assigned',
  ISSUE_UPDATED = 'issue_updated',
  ISSUE_COMMENTED = 'issue_commented',
  ISSUE_STATUS_CHANGED = 'issue_status_changed',
  ISSUE_PRIORITY_CHANGED = 'issue_priority_changed',
  ISSUE_DUE_DATE_CHANGED = 'issue_due_date_changed',
  COMMENT_ON_ISSUE = 'comment_on_issue',
  COMMENT_MENTION = 'comment_mention',
  COMMENT_REPLY = 'comment_reply',
  MENTION = 'mention',
  SPRINT_STARTED = 'sprint_started',
  SPRINT_COMPLETED = 'sprint_completed',
  PROJECT_INVITATION = 'project_invitation',
}
