export enum NotificationType {
  ISSUE_ASSIGNED = 'issue_assigned',
  ISSUE_UPDATED = 'issue_updated',
  ISSUE_COMMENTED = 'issue_commented',
  ISSUE_STATUS_CHANGED = 'issue_status_changed',
  ISSUE_PRIORITY_CHANGED = 'issue_priority_changed',
  ISSUE_DUE_DATE_CHANGED = 'issue_due_date_changed',
  COMMENT_ON_ISSUE = 'comment_on_issue',
  COMMENT_MENTION = 'comment_mention',
  COMMENT_REPLY = 'comment_reply',
  MENTION = 'mention',
  SPRINT_STARTED = 'sprint_started',
  SPRINT_COMPLETED = 'sprint_completed',
  SPRINT_ISSUE_ADDED = 'sprint_issue_added',
  SPRINT_STARTING_SOON = 'sprint_starting_soon',
  SPRINT_ENDING_SOON = 'sprint_ending_soon',
  PROJECT_INVITATION = 'project_invitation',
  PROJECT_MEMBER_ADDED = 'project_member_added',
  PROJECT_MEMBER_REMOVED = 'project_member_removed',
  PROJECT_ROLE_CHANGED = 'project_role_changed',
  PROJECT_ARCHIVED = 'project_archived',
  PROJECT_DELETED = 'project_deleted',
  FEEDBACK_UPVOTED = 'feedback_upvoted',
  FEEDBACK_STATUS_CHANGED = 'feedback_status_changed',
  FEEDBACK_COMMENTED = 'feedback_commented',
  NEW_CHANGELOG = 'new_changelog',
}
